main.exe tests/TEST-0.bmp results/TEST-0-O.bmp laplacian
main.exe tests/TEST-1.bmp results/TEST-1-O.bmp laplacian
main.exe tests/TEST-2.bmp results/TEST-2-O.bmp laplacian
main.exe tests/TEST-3.bmp results/TEST-3-O.bmp laplacian
main.exe tests/TEST-4.bmp results/TEST-4-O.bmp mean
main.exe tests/TEST-5.bmp results/TEST-5-O.bmp mean
main.exe tests/TEST-6.bmp results/TEST-6-O.bmp mean
main.exe tests/TEST-7.bmp results/TEST-7-O.bmp mean
main.exe tests/TEST-8.bmp results/TEST-8-O.bmp laplacian
main.exe tests/TEST-9.bmp results/TEST-9-O.bmp mean